CREATE TABLE planets(
   id SERIAL NOT NULL PRIMARY KEY,
   name VARCHAR(255) NOT NULL,
   cord_x INTEGER NOT NULL,
   cord_Y INTEGER NOT NULL,
   created_at TIMESTAMP(6) NOT NULL,
   updated_at TIMESTAMP(6) NOT NULL
);